name: optimizer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - adwaita-icon-theme=48.1
  - alembic=1.15.1
  - alsa-lib=1.2.13
  - aom=3.9.1
  - asttokens=3.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - augustus=3.5.0
  - bamtools=2.5.2
  - bbmap=39.19
  - binutils_impl_linux-64=2.43
  - biopython=1.85
  - blast=2.16.0
  - boost-cpp=1.85.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - busco=5.8.3
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.7.9
  - cairo=1.18.4
  - cdbtools=0.99
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clustalw=2.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.10.18
  - curl=8.12.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.13
  - decorator=5.2.1
  - dendropy=5.0.6
  - deprecated=1.2.18
  - diamond=2.1.11
  - dnspython=2.7.0
  - double-conversion=3.3.1
  - entrez-direct=22.4
  - epoxy=1.5.10
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fasttree=2.1.11
  - fftw=3.3.10
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.5.1
  - gawk=5.3.1
  - gcc_impl_linux-64=14.2.0
  - gdk-pixbuf=2.42.12
  - gfastats=1.3.11
  - gfortran_impl_linux-64=14.2.0
  - ghostscript=10.04.0
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glib-tools=2.84.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - graphviz=12.2.1
  - greenlet=3.1.1
  - gsl=2.7
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx_impl_linux-64=14.2.0
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hicolor-icon-theme=0.17
  - hifiasm=0.25.0
  - hmmer=3.4
  - hpack=4.1.0
  - htslib=1.21
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagemagick=7.1.1_46
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - k8=1.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libasprintf=0.23.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=20.1.1
  - libcups=2.3.3
  - libcurl=8.12.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgettextpo=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - libllvm20=20.1.1
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopenssl-static=3.4.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.28.3
  - librsvg=2.58.4
  - libsanitizer=14.2.0
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.1
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lp_solve=5.5.2.11
  - mafft=7.526
  - make=4.4.1
  - mako=1.3.9
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - metaeuk=7.bba0d80
  - metis=5.1.0
  - minimap2=2.30
  - miniprot=0.14
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.0.7
  - muscle=3.8.1551
  - mysql-common=9.0.1
  - mysql-connector-c=6.1.11
  - mysql-libs=9.0.1
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - openjdk=23.0.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - optree=0.16.0
  - optuna=4.2.1
  - optunahub=0.3.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.3
  - parso=0.8.4
  - pasta=1.9.2
  - pcre=8.45
  - pcre2=10.44
  - perl=5.32.1
  - perl-apache-test=1.43
  - perl-app-cpanminus=1.7048
  - perl-archive-tar=2.40
  - perl-base=2.23
  - perl-carp=1.38
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.13
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-constant=1.33
  - perl-cpan-meta-check=0.014
  - perl-cpan-meta-requirements=2.143
  - perl-data-optlist=0.113
  - perl-dbi=1.643
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.007
  - perl-devel-stacktrace=2.04
  - perl-dist-checkconflicts=0.11
  - perl-encode=3.19
  - perl-eval-closure=0.14
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-path=2.18
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-getopt-long=2.58
  - perl-inc-latest=0.500
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-module-build=0.4234
  - perl-module-implementation=0.09
  - perl-module-metadata=1.000038
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.005004
  - perl-moose=2.2202
  - perl-mro-compat=0.15
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.40
  - perl-package-stash-xs=0.30
  - perl-parallel-forkmanager=2.03
  - perl-params-util=1.102
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-role-tiny=2.002004
  - perl-scalar-list-utils=1.62
  - perl-storable=3.15
  - perl-sub-exporter=0.988
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.006006
  - perl-test-fatal=0.016
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-version=0.9924
  - perl-xsloader=0.24
  - perl-yaml=1.30
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pkg-config=0.29.2
  - platformdirs=4.3.7
  - plotly=6.0.1
  - prank=170427
  - prodigal=2.6.3
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygithub=2.6.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pymongo=4.11
  - pynacl=1.5.0
  - pyparsing=3.2.2
  - pyside6=6.8.2
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.3.0
  - qhull=2020.2
  - qt6-main=6.8.2
  - r-base=4.4.3
  - r-cli=3.6.4
  - r-colorspace=2.1_1
  - r-crayon=1.5.3
  - r-ellipsis=0.3.2
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-ggplot2=3.5.1
  - r-glue=1.8.0
  - r-gtable=0.3.6
  - r-isoband=0.2.7
  - r-labeling=0.4.3
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_64
  - r-matrix=1.7_3
  - r-mgcv=1.9_1
  - r-munsell=0.5.1
  - r-nlme=3.1_167
  - r-pillar=1.10.1
  - r-pkgconfig=2.0.3
  - r-r6=2.6.1
  - r-rcolorbrewer=1.1_3
  - r-rlang=1.1.5
  - r-scales=1.3.0
  - r-tibble=3.2.1
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-withr=3.0.2
  - rav1e=0.7.1
  - raxml=8.2.13
  - readline=8.2
  - requests=2.32.3
  - rpsbproc=0.5.0
  - samtools=1.21
  - sed=4.8
  - sepp=4.5.5
  - seqtk=1.4
  - setuptools=75.8.2
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.2
  - sniffio=1.3.1
  - sqlalchemy=2.0.39
  - sqlite=3.49.1
  - stack_data=0.6.3
  - suitesparse=5.10.1
  - svt-av1=3.0.2
  - sympy=1.14.0
  - sysroot_linux-64=2.17
  - tar=1.34
  - tbb=2022.0.0
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucsc-fatotwobit=472
  - ucsc-twobitinfo=472
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wget=1.21.4
  - wheel=0.45.1
  - wrapt=1.17.2
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - sniffles
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - attrs==25.3.0
      - cryptography==45.0.5
      - fastjsonschema==2.21.1
      - gfapy==1.2.3
      - ipython==8.35.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - narwhals==1.32.0
      - nbformat==5.10.4
      - numpy==2.2.5
      - referencing==0.36.2
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - threadpoolctl==3.6.0
